name: 3D Contribution Calendar

on:
  schedule:
    - cron: "0 18 * * *"   # runs daily at midnight IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph

    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: 1MZORO
        with:
          MAX_REPOS: 10
          SETTING_JSON: |
            {
              "username": "1MZORO",
              "max_repos": 10,
              "selectedBranch": "main",
              "animation": true,
              "antiAlias": true,
              "isDebug": false,
              "backgroundColor": "0d1117",
              "strongColor": "00F7FF",
              "lightColor": "7B2FBE"
            }

      - name: Push to repo
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          add: "profile-3d-contrib"
