name: 3D Contribution Calendar

on:
  schedule:
    - cron: "0 18 * * *"   # runs daily at midnight IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate 3D Contribution Graph
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          USERNAME: 1MZORO

      - name: Commit files
        uses: EndBug/add-and-commit@v9
        with:
          add: "profile-3d-contrib"
          message: "generated 3D contribution graph"